- hosts: swarm-manager
  become: yes
  tasks:
    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    - name: Clone repository
      git:
        repo: 'https://github.com/rbrinkke/infrastructure.git'
        dest: /home/rob/repos/infrastructure
        update: yes
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: /home/rob/repos/infrastructure/terraform
    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: /home/rob/repos/infrastructure/terraform
    - name: Run Ansible Playbook
      command: ansible-playbook playbook.yml -i inventory.yml
      args:
        chdir: /home/rob/repos/infrastructure/ansible
