name: Check Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Test Secrets
        run: |
          echo "Testing GitHub Secrets:"
          echo "DOCKER_USERNAME: ${DOCKER_USERNAME:+Set}"
          echo "DOCKER_PASSWORD: ${DOCKER_PASSWORD:+Set}"
          echo "SSH_KEY: ${SSH_KEY:+Set}"
          echo "SWARM_HOST: ${SWARM_HOST:+Set}"
          echo "SWARM_USER: ${SWARM_USER:+Set}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SWARM_HOST: ${{ secrets.SWARM_HOST }}
          SWARM_USER: ${{ secrets.SWARM_USER }}

