---
name: Build and Push Docker Image

on:
  workflow_dispatch:  # Trigger workflow manually

jobs:
  build:
    runs-on: ubuntu-20.04  # Gebruik een stabiele versie om de waarschuwing te vermijden

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo curl -L \
            "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" \
            -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and Push Docker Compose Image
        run: |
          docker-compose build && \
          docker-compose push

